name: skilla
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+12

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  cupertino_icons: ^0.1.3
  # Used to generating files 
  build_runner: ^1.10.0
  # Used to make the on board Screen
  introduction_screen: ^1.0.7
  # Used to make the splash Screen
  splashscreen: ^1.2.0
  # Used to json serialization
  json_annotation: ^3.0.1
  json_serializable: ^3.3.0
  # Used to provide internationalization and localization facilities
  intl: ^0.16.1
  # Used to handler events on app
  event: ^1.1.4
  # Used to create snack bar without context
  flushbar: ^1.10.4
  # Used to get the feather icons
  feather_icons_flutter: ^4.7.4
  # Used to get the font awesome icons
  font_awesome_flutter: ^8.10.0
  # Used to handler http requests
  dio: ^3.0.10
  # Used to handler database
  sqflite: ^1.3.0
  # Used to get app version
  package_info: ^0.4.3
  # Used to get device ID
  device_info: ^0.4.2+7
  # Used to find locations on filesystem
  path_provider: ^1.6.14
  # Used to logs network calls in a pretty format.
  pretty_dio_logger: ^1.1.1
  # Used to load and cache images from url
  cached_network_image: ^2.2.0+1
  # Used to render pdf files
  native_pdf_view: ^3.8.0
  # Used to formatter dates
  jiffy: ^3.0.1
  # Used to access the gallery
  image_picker: ^0.6.7+12
  # Used to handler list view (pull to refresh and load more)
  pull_to_refresh: ^1.6.1
  # Used to launch url
  url_launcher: ^5.7.10
  # Used to make a bottomBar
  bottom_navy_bar: ^5.5.0
  # Used to handler notifications
  firebase_messaging: ^7.0.1
  # Used to handle google analytics
  firebase_analytics: ^6.2.0
  # Used to handle dynamic links
  firebase_dynamic_links: ^0.6.2
  # Used to put ADS in the app
  firebase_admob: ^0.10.2
  # Used to report errors thrown by your program to https://sentry.io error tracking service.
  sentry: ">=3.0.0 <4.0.0"
  # Used to share posts
  share: ^0.6.5+4
  # Used to get the Google fonts
  google_fonts: ^1.1.1
  # Used to crop images
  image_cropper: ^1.3.1
  # Used zoom image widget for Flutter.
  photo_view: ^0.10.3
  # Used to navigate
  get: ^3.17.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - i18n/en.json
    - i18n/pt.json
    - i18n/es.json
    - assets/